### ISSUE TITLE
打砖块：球的运动规律得不科学

### ISSUE THREAD

**Issue by cjh0613** [liuyib/my-games#1]
打砖块：球的运动太有规律了。
打第一关最后两块砖的时候，一直在无限循环一种路径，就是碰不到砖。

**Comment by liuyib** [comment]
之前为了简单，直接碰撞后原路返回，后面做了改进 [cc67a86](https://github.com/liuyib/game/commit/cc67a86148f624cdba6ddbb8a4384c6d54dbd6d5)，小球返回时，角度会有微小的随机化。

**Comment by liuyib** [comment]
游戏还是很粗糙的，哈哈哈
